# Generated by Django 4.2.6 on 2023-10-23 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('total_fat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementQty',
            fields=[
                ('qty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('qty_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnits',
            fields=[
                ('unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('measurement_desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=30)),
                ('role_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_pass', models.CharField(max_length=50)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_desc', models.CharField(max_length=10000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.users')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.ingredients')),
                ('qty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.measurementqty')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.recipes')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.measurementunits')),
            ],
        ),
    ]
