# Generated by Django 4.2.6 on 2023-12-01 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('measure', models.CharField(max_length=100)),
                ('grams', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('fat', models.CharField(max_length=10)),
                ('sat_fat', models.CharField(max_length=10)),
                ('fiber', models.CharField(max_length=10)),
                ('carbs', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementQty',
            fields=[
                ('qty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('qty_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnits',
            fields=[
                ('unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('measurement_desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=30)),
                ('role_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_pass', models.CharField(max_length=50)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_desc', models.CharField(max_length=10000)),
                ('recipe_ingredients', models.CharField(max_length=500)),
                ('recipe_preptime', models.IntegerField()),
                ('recipe_cooktime', models.IntegerField()),
                ('recipe_peanut', models.BooleanField(default=False)),
                ('recipe_Dairy', models.BooleanField(default=False)),
                ('recipe_vegetarian', models.BooleanField(default=False)),
                ('recipe_vegan', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('recipe_ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.ingredients')),
                ('qty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.measurementqty')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.recipes')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.measurementunits')),
            ],
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_amount', models.IntegerField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.ingredients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
