# Generated by Django 4.2.1 on 2023-11-17 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_alter_pantryitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.users'),
        ),
    ]
