# Generated by Django 4.2.1 on 2023-11-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_pantryitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
