# Generated by Django 4.2.1 on 2023-12-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_pantryitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='carbohydrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
