# Generated by Django 4.2.1 on 2023-12-22 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpage', '0015_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
            ],
            options={
                'db_table': 'webpage_recipesmade',
            },
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='qty_id',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='MeasurementQty',
        ),
        migrations.DeleteModel(
            name='MeasurementUnits',
        ),
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
